# -*- coding: utf-8 -*-
"""Copy of Simple Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxJkz3AXVY943STruqfT6HvVuMaqIWPC

# **Step 1: Import all the required Libraries**
"""

import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

"""# **Step 2 : Load the California housing Dataset**"""

housing = fetch_california_housing()
#housing

"""# **Step 3: Get the feature, Labels and get some Basic Information from the Data**"""

X = housing.data
y = housing.target

X = pd.DataFrame(X, columns=housing.feature_names)
y = pd.DataFrame(y, columns=["MedHouseVal"])

#X.info()
#X.describe()

#X.isnull().sum()
#y.isnull().sum()

display(X.duplicated().sum())

y.head()

"""# **Step 4: Train-test Split**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

"""# **Step 5: Model Training**"""

model = LinearRegression()
model.fit(X_train,y_train)

"""# **Step 6: Evaluate the model**"""

y_pred = model.predict(X_test)
print(y_pred)

#y_pred = pd.DataFrame(y_pred, columns=["Predicted"])

#y_pred = y_pred.merge(X_test, left_index=True, right_index=True)

#y_pred.head()


mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)

"""# **Polynomial Regression**

# **Step 1: Import all the required Libraries**
"""

import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

"""# **Step 2: Load the Dataset**"""

housing= fetch_california_housing()
housing

X = pd.DataFrame(housing.data, columns=housing.feature_names)
#X = X["MedInc"]
y = pd.DataFrame(housing.target, columns=["MedHouseVal"])

X.head()
#y.head()

"""# **Step 3 : Polynomial Degree and Train-test Split**"""

Poly_Features = PolynomialFeatures(degree=3)

# Reshape X to be a 2D array as PolynomialFeatures expects a 2D input
X_Poly = Poly_Features.fit_transform(X.values.reshape(-1, 1))

X_train, X_test, y_train, y_test = train_test_split(X_Poly, y, test_size=0.2, random_state=42)

X_train.shape

X_test.shape

X.values.reshape(-1, 1)

"""# **Step 4: Model Training**"""

model = LinearRegression()
model.fit(X_train,y_train)

"""# **Step 5: Model Evaluation**"""

y_pred = model.predict(X_test)
print(y_pred)

"""# **Step 6: Calculate MAE, MSE, RMSE, R2 Score**"""

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)

